version: 2

############################################################################

references:
   default_environment_settings: &default_environment_settings
      docker:
        - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      environment:
        - ANT_OPTS: -Dzimbra.buildinfo.version=8.7.6_GA
        - BUILD: "/home/ubuntu"
        - CIRCLE_TEST_REPORTS: "/tmp"
      working_directory: /home/ubuntu/zm-mailbox
   default_attach_workspace: &default_attach_workspace
         attach_workspace:
            at: /home/ubuntu
   filter_branches: &filter_branches
     filters:
       branches:
         only:
           - develop
           - circleci-20-test
############################################################################

jobs:
  build:
    <<: *default_environment_settings
    steps:
      - checkout
      - run:
          name: Install ant-contrib and nodejs-legacy
          command: sudo apt-get update; sudo apt-get install ant-contrib nodejs-legacy npm
      - run:
          name: Install junit-merge
          command: sudo npm config set strict-ssl false && sudo npm install -g junit-merge
      - run:
          name: Clone zm-timezones
          command: |
            cd "$BUILD"
            git clone https://github.com/Zimbra/zm-timezones.git -b develop --single-branch || exit 1
      - run:
          command: ant clean compile publish-local
          working_directory: native
      - run:
          command: ant clean compile publish-local
          working_directory: common
      - run:
          command: ant clean compile publish-local
          working_directory: soap
      - run:
          command: ant clean compile publish-local
          working_directory: client
      - run:
          command: ant clean compile publish-local
          working_directory: store
      - persist_to_workspace:
          root: /home/build/
          paths:
            - zm-timezones
            - zm-mailbox
            - .ssh
############################################################################

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          <<: *filter_branches
############################################################################
