version: 2

############################################################################

references:
   default_environment_settings: &default_environment_settings
      docker:
        - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      environment:
        - ANT_OPTS: -Dzimbra.buildinfo.version=8.7.6_GA
        - BUILD: "/home/build"
        - CIRCLE_TEST_REPORTS: "/tmp"
      working_directory: /home/build/zm-mailbox
   default_attach_workspace: &default_attach_workspace
         attach_workspace:
            at: /home/build/
   filter_branches: &filter_branches
     filters:
       branches:
         only:
           - develop
           - circleci-20-test
############################################################################

jobs:
  build:
    <<: *default_environment_settings
    steps:
      - checkout
      - run:
          name: Install ant-contrib and nodejb-legacy
          command: sudo apt-get update; sudo apt-get install ant-contrib nodejs-legacy
      - run:
          name: Install junit-merge
          command: npm install -g junit-merge
      - run:
          name: Clone zm-timezones
          command: |
            cd "$BUILD"
            git clone https://github.com/Zimbra/zm-timezones.git -b develop --single-branch: || exit 1
      - run:
          command: ant clean compile publish-local
          working_directory: native
      - run:
          command: ant clean compile publish-local
          working_directory: common
      - run:
          command: ant clean compile publish-local
          working_directory: soap
      - run:
          command: ant clean compile publish-local
          working_directory: client
      - run:
          command: ant clean compile publish-local
          working_directory: store
      - persist_to_workspace:
          root: /home/build/
          paths:
            - zm-timezones
            - zm-mailbox
            - .ssh
  test:
    <<: *default_environment_settings
    steps:
      - *default_attach_workspace
      - run: 
          name: Create test report directory to hold junit tests
          command: mkdir -p $CIRCLE_TEST_REPORTS/junit/
      - run:
        command: ant test
        working_directory: native
      - run:
        command: ant test
        working_directory: common
      - run:
        command: ant test
        working_directory: soap
      - run:
        command: ant test
        working_directory: client
      - run:
        command: ant test
        no_output_timeout: 1200s
        working_directory: store
      - run: 
        name: Find test results
        command: find . -type f -regex ".*/build/test/report/.*xml" | xargs junit-merge
      - run: 
        name: Copy test results to proper directory 
        command: cp merged-test-results.xml $CIRCLE_TEST_REPORTS/junit/
      - store_test_results:
        path: $CIRCLE_TEST_REPORTS/junit/
############################################################################

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          <<: *filter_branches
      - test:
          requires:
            - build
          <<: *filter_branches
############################################################################
